### ISSUE TITLE
[Any/all] No detours getting hit + OnClientPreConnectEx not firing

### ISSUE THREAD

**Issue by Nik1Toxic** [asherkin/connect#19]
After the new TF2 update, this extension causes an error in the console:
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils 004 before SteamAPI_Init succeeded.

The server continues to work, but when connecting, the error "Steam validation rejected" appears

**Comment by asherkin** [comment]
Seems likely this is a change to the layout of CSteam3Server? Not sure why I never put that in gamedata, it was in SteamTools2...

**Comment by sapphonie** [comment]
Not resolved by #20, still an issue.

**Comment by sapphonie** [comment]
Info I've found:

- None of the detours are getting hit in gdb
- Extension loads fine, throws no errors in OnLoad, returns true

**Comment by Natanel-Shitrit** [comment]
> Info I've found:
> 
> * None of the detours are getting hit in gdb
> * Extension loads fine, throws no errors in OnLoad, returns true

Have you checked if it works after commit fa6bf9c44ca8a10bcb292860f3b54aa6e0f02dc6?
It changed the `AMBuildScript` to use `CDetours` from SM instead of the included one. (no idea if it really fixes anything)

**Comment by sapphonie** [comment]
> > Info I've found:
> > 
> > * None of the detours are getting hit in gdb
> > * Extension loads fine, throws no errors in OnLoad, returns true
> 
> Have you checked if it works after commit fa6bf9c44ca8a10bcb292860f3b54aa6e0f02dc6?
> It changed the `AMBuildScript` to use `CDetours` from SM instead of the included one. (no idea if it really fixes anything)
> 

Yes, this was on a recent commit, double check me though if you'd like in case I'm misremembering...

**Comment by Natanel-Shitrit** [comment]
> > > Info I've found:
> > > 
> > > * None of the detours are getting hit in gdb
> > > * Extension loads fine, throws no errors in OnLoad, returns true
> > 
> > 
> > Have you checked if it works after commit [fa6bf9c](https://github.com/asherkin/connect/commit/fa6bf9c44ca8a10bcb292860f3b54aa6e0f02dc6)?
> > It changed the `AMBuildScript` to use `CDetours` from SM instead of the included one. (no idea if it really fixes anything)
> 
> Yes, this was on a recent commit, double check me though if you'd like in case I'm misremembering...

I have no TF2 setup 😢
It fixed a crash in #21 I thought it might fix other things here too

**Comment by khalik38** [comment]
> 40 dollar paypal bounty on anyone who wants to PR something that fixes this 👍

If someone fixes this, I shall contribute towards this.

No detours getting hit + OnClientPreConnectEx not firing

**Comment by sapphonie** [comment]
@Kenzzer
